# Generated by Django 5.2.7 on 2025-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ملف مستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='نبذة عن المستخدم'),
        ),
    ]
