# Generated by Django 5.2.7 on 2025-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='magazines/covers/', verbose_name='غلاف المجلة'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='magazines/videos/', verbose_name='فيديو تعريفي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
    ]
