# Generated by Django 5.2.7 on 2025-10-30 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_magazine_cover_magazine_preview_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='preview_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='فيديو تعريفي'),
        ),
    ]
